# Generated by Django 5.2.6 on 2025-10-02 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usersettings_notify_on_hate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('twitter', 'Twitter')], db_index=True, max_length=20)),
                ('external_id', models.CharField(db_index=True, help_text='Comment ID or unique external identifier', max_length=100)),
                ('media_id', models.CharField(blank=True, max_length=100, null=True)),
                ('comment_text', models.TextField(blank=True)),
                ('sentiment_label', models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral'), ('hate', 'Hate')], max_length=20, null=True)),
                ('needs_approval', models.BooleanField(default=False)),
                ('ai_response', models.TextField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'platform'], name='notificatio_user_id_3a5227_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx')],
                'unique_together': {('user', 'platform', 'external_id')},
            },
        ),
    ]
