# Generated by Django 5.2.7 on 2025-10-28 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_device'),
        ('instagram', '0002_instagramaccount_account_type_and_more'),
        ('shopify_integration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='auto_comment_enabled',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='auto_respond_to_hate',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='auto_respond_to_negative',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='auto_respond_to_positive',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='notify_on_hate',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='notify_on_negative',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='notify_on_neutral',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='notify_on_positive',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='notify_on_purchase_intent',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='notify_on_question',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='require_approval_for_hate',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='require_approval_for_negative',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='response_style',
        ),
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('generated_image_path', models.CharField(blank=True, max_length=500, null=True)),
                ('caption', models.TextField()),
                ('instagram_media_id', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram_permalink', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating Image'), ('posting', 'Posting to Instagram'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('instagram_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagram.instagramaccount')),
                ('shopify_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopify_integration.shopifystore')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'instagram_posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.AddIndex(
            model_name='instagrampost',
            index=models.Index(fields=['user', 'status'], name='instagram_p_user_id_8ec0c4_idx'),
        ),
        migrations.AddIndex(
            model_name='instagrampost',
            index=models.Index(fields=['review_id'], name='instagram_p_review__416d76_idx'),
        ),
        migrations.AddIndex(
            model_name='instagrampost',
            index=models.Index(fields=['instagram_media_id'], name='instagram_p_instagr_b3c7e6_idx'),
        ),
    ]
