# Generated by Django 5.2.7 on 2025-10-28 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_domain', models.CharField(max_length=255, unique=True)),
                ('access_token', models.TextField()),
                ('store_name', models.CharField(max_length=255)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('primary_color', models.CharField(default='#000000', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopify_stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shopify_stores',
                'ordering': ['-installed_at'],
            },
        ),
        migrations.CreateModel(
            name='JudgeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(max_length=255, unique=True)),
                ('rating', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('body', models.TextField()),
                ('reviewer_name', models.CharField(max_length=255)),
                ('product_title', models.CharField(max_length=500)),
                ('product_image_url', models.URLField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shopify_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shopify_integration.shopifystore')),
            ],
            options={
                'db_table': 'judge_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shopifystore',
            index=models.Index(fields=['user', 'is_active'], name='shopify_sto_user_id_f02f0c_idx'),
        ),
        migrations.AddIndex(
            model_name='shopifystore',
            index=models.Index(fields=['shop_domain'], name='shopify_sto_shop_do_1f58c8_idx'),
        ),
        migrations.AddIndex(
            model_name='judgereview',
            index=models.Index(fields=['shopify_store', 'processed'], name='judge_revie_shopify_c84734_idx'),
        ),
        migrations.AddIndex(
            model_name='judgereview',
            index=models.Index(fields=['review_id'], name='judge_revie_review__cbc372_idx'),
        ),
        migrations.AddIndex(
            model_name='judgereview',
            index=models.Index(fields=['rating'], name='judge_revie_rating_929ed9_idx'),
        ),
    ]
