# Generated by Django 5.2.7 on 2025-10-11 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_hosted', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usagelog',
            new_name='usage_logs_api_use_600dce_idx',
            old_name='usage_logs_api_use_a7b8e1_idx',
        ),
    ]
