# Generated by Django 5.2.7 on 2025-10-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_hosted', '0002_rename_usage_logs_api_use_a7b8e1_idx_usage_logs_api_use_600dce_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='is_pro',
            field=models.BooleanField(default=False, help_text='Pro subscription status'),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='projects_remaining',
            field=models.IntegerField(default=3, help_text='Number of free validations remaining'),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe customer ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='subscription_id',
            field=models.CharField(blank=True, help_text='Stripe subscription ID', max_length=255, null=True),
        ),
    ]
