# Generated by Django 5.2.4 on 2025-09-30 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('access_token', models.CharField(max_length=500)),
                ('refresh_token', models.CharField(blank=True, max_length=500, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instagram_user_id', models.CharField(max_length=100, unique=True)),
                ('profile_picture_url', models.URLField(blank=True, null=True)),
                ('followers_count', models.IntegerField(default=0)),
                ('following_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instagram Account',
                'verbose_name_plural': 'Instagram Accounts',
                'db_table': 'instagram_accounts',
            },
        ),
        migrations.CreateModel(
            name='InstagramWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_id', models.CharField(max_length=100, unique=True)),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='instagram.instagramaccount')),
            ],
            options={
                'db_table': 'instagram_webhooks',
                'ordering': ['-created_at'],
            },
        ),
    ]
