# Generated by Django 5.2.4 on 2025-09-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='account_type',
            field=models.CharField(choices=[('PERSONAL', 'Personal Account'), ('BUSINESS', 'Business Account')], default='PERSONAL', max_length=20),
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='expires_in',
            field=models.IntegerField(blank=True, help_text='Token expiration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='media_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='token_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='token_type',
            field=models.CharField(default='bearer', max_length=50),
        ),
        migrations.AlterField(
            model_name='instagramaccount',
            name='access_token',
            field=models.TextField(help_text='Instagram access token'),
        ),
        migrations.AlterField(
            model_name='instagramaccount',
            name='refresh_token',
            field=models.TextField(blank=True, help_text='Refresh token if available', null=True),
        ),
    ]
